var car = 'Thar';
console.log("Is car == 'Thar'? I predict True.");
console.log(car == 'Thar');
var bestie = 'Zaira';
console.log("Is bestfriend == 'zaira'? I predict True");
console.log(bestie == 'Zaira');
var food = 'chowmein';
console.log("Is food == 'chowmein'? I predict true.");
console.log(food == 'chowmein');
var city = 'Karbala';
console.log("Is city == 'Karbala'? I predict True.");
console.log(city == 'Karbala');
var hobby = 'reading';
console.log("Is hobby == 'reading'? I predict True.");
console.log(hobby == 'reading');
var car1 = 'Rolls royce';
console.log("Is car1 == 'Thar'? I predict false.");
console.log(car == 'rolls royce');
var bestie1 = 'Zarmeen';
console.log("Is bestfriend == 'zaira'? I predict false");
console.log(bestie == 'Zarmeen');
var food1 = 'Pizza';
console.log("Is food == 'chowmein'? I predict false.");
console.log(food == 'Pizza');
var city1 = 'mashad';
console.log("Is city == 'Karbala'? I predict false.");
console.log(city == 'Mashad');
var hobby1 = 'writing';
console.log("Is hobby == 'reading'? I predict false.");
console.log(hobby == 'writing');
